services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "authentik_password"
      POSTGRES_USER: "authentik"
      POSTGRES_DB: "authentik"
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentik-server:
    image: ghcr.io/goauthentik/server:2024.2.2
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: "authentik"
      AUTHENTIK_POSTGRESQL__NAME: "authentik"
      AUTHENTIK_POSTGRESQL__PASSWORD: "authentik_password"
      AUTHENTIK_SECRET_KEY: "very-secret-key-12345"
      AUTHENTIK_HOST_BROWSER: http://localhost:9000
    volumes:
      - ./media:/media
      - ./templates:/templates
    ports:
      - "9000:9000"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  hello-world:
    image: crccheck/hello-world
    container_name: gatekeeper-hello-world
    platform: linux/amd64

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    command: ["run", "--server", "--addr=0.0.0.0:8181", "/policies"]
    volumes:
      - ./opa/policies:/policies
    ports:
      - "8181:8181"

  worker:
    image: ghcr.io/goauthentik/server:2024.2.2
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: "authentik"
      AUTHENTIK_POSTGRESQL__NAME: "authentik"
      AUTHENTIK_POSTGRESQL__PASSWORD: "authentik_password"
      AUTHENTIK_SECRET_KEY: "very-secret-key-12345"
      AUTHENTIK_HOST_BROWSER: http://localhost:9000
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy